from fastapi import FastAPI, HTTPException, status
from pydantic import BaseModel, Field

from gemini_service import (
    DEFAULT_MODEL,
    GeminiServiceError,
    MAX_PROMPT_LENGTH,
    generate_response,
    is_api_configured,
)
from prompts import get_tutor_system_prompt

app = FastAPI(
    title="LearnMate AI API",
    description="REST API service for LearnMate AI - Personalized Learning Tutor (SDG 4: Quality Education)",
    version="0.1.0",
)


class ChatRequest(BaseModel):
    message: str = Field(
        ...,
        description="The student's question, academic problem, or concept query.",
        min_length=1,
        max_length=MAX_PROMPT_LENGTH,
        examples=["Explain photosynthesis in simple terms"],
    )


class ChatResponse(BaseModel):
    response: str = Field(
        ...,
        description="The educational response and check question generated by the tutor.",
    )


@app.get("/health", status_code=status.HTTP_200_OK)
def health_check():
    """Simple health check endpoint returning server status."""
    return {"status": "ok"}


@app.get("/")
def read_root():
    """Information root endpoint describing API capabilities and service readiness."""
    return {
        "project": "LearnMate AI",
        "sdg_goal": "SDG 4 - Quality Education",
        "status": "online",
        "gemini_api_configured": is_api_configured(),
        "endpoints": {
            "health": "GET /health",
            "chat": "POST /chat",
            "documentation": "GET /docs",
        },
    }


@app.post(
    "/chat",
    response_model=ChatResponse,
    status_code=status.HTTP_200_OK,
    summary="Chat with LearnMate AI Tutor",
    responses={
        200: {"description": "Successful tutor response generated."},
        400: {"description": "Invalid input: empty or whitespace message."},
        503: {"description": "Tutor service unconfigured or Gemini API key missing."},
        502: {"description": "Upstream communication error with Gemini service."},
    },
)
def chat_with_tutor(payload: ChatRequest):
    """
    Receives a student message, executes the same SDG 4 educational tutor logic
    used by the Streamlit application, and returns the tutor's response.
    """
    cleaned_message = payload.message.strip()
    if not cleaned_message:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="The 'message' field cannot be empty or whitespace only.",
        )

    if not is_api_configured():
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="Tutor service unavailable: GEMINI_API_KEY is not configured on the server.",
        )

    # Use the identical pedagogical system prompt used by the Streamlit app
    system_instruction = get_tutor_system_prompt(learner_level="Intermediate")

    try:
        tutor_response = generate_response(
            prompt=cleaned_message,
            system_instruction=system_instruction,
            model=DEFAULT_MODEL,
        )
        return ChatResponse(response=tutor_response)
    except GeminiServiceError as err:
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail=f"Tutor service error: {str(err)}",
        )
    except Exception:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="An unexpected internal error occurred while generating the tutor response.",
        )
